version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           git clone https://github.com/zhantech/device_xiaomi_santoni-twrp -b PBRP
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
